[book]
authors = ["buttercrab"]
language = "en"
multilingual = false
src = "src"
title = "IamCoder Wiki"
html header: <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
